name: Continuous Integration

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt -q install valgrind
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-coverage --enable-valgrind
    - name: make
      run: make
    - name: make check
      run: make check || (grep . test/*.log; false)
    - name: Generate coverage reports
      run: |
        ./gencov lib/*.c src/*.c
        mkdir artifacts
        tar cf - lib/*.gcov src/*.gcov | tar -C artifacts -xf -
    - name: Upload coverage-annotated source files
      uses: actions/upload-artifact@v1
      with:
        path: "artifacts"
        name: coverage_reports
